export default [{
  name: 'Flash',
  model: '../assets/characters/2025/flash-sprint.glb',
  isActive: true,
  price: 0,
  isLocked: false,
  isGlb: true,
  danceAnimation: '../assets/characters/2025/flash-sprint.glb',
  runAnimation: '../assets/characters/2025/flash-sprint.glb',
  slideAnimation: '../assets/characters/2025/flash-sprint.glb',
  stumbleAnimation: '../assets/characters/2025/flash-sprint.glb',
  jumpAnimation: '../assets/characters/2025/flash-sprint.glb',
},
{
  name: 'Xbot',
  model: '../assets/characters/xbot.fbx',
  isActive: false,
  price: 0,
  isLocked: false,
  danceAnimation: './assets/animations/xbot@dancing.fbx',
  runAnimation: '../assets/animations/xbot@running.fbx',
  slideAnimation: '../assets/animations/xbot@sliding.fbx',
  stumbleAnimation: '../assets/animations/xbot@stumbling.fbx',
  jumpAnimation: '../assets/animations/xbot@jumping.fbx',
},
{
  name: 'Jolleen',
  model: '../assets/characters/jolleen.fbx',
  isActive: false,
  price: 200,
  isLocked: true,
  danceAnimation: '../assets/animations/jolleen@dancing.fbx',
  runAnimation: '../assets/animations/jolleen@running.fbx',
  slideAnimation: '../assets/animations/jolleen@sliding.fbx',
  stumbleAnimation: '../assets/animations/jolleen@stumbling.fbx',
  jumpAnimation: '../assets/animations/jolleen@jumping.fbx',
},
{
  name: 'Peasant Girl',
  model: '../assets/characters/peasant-girl.fbx',
  isActive: false,
  price: 4000,
  isLocked: true,
  danceAnimation: '../assets/animations/peasant-girl@dancing.fbx',
  runAnimation: '../assets/animations/peasant-girl@running.fbx',
  slideAnimation: '../assets/animations/peasant-girl@sliding.fbx',
  stumbleAnimation: '../assets/animations/peasant-girl@stumbling.fbx',
  jumpAnimation: '../assets/animations/peasant-girl@jumping.fbx',
},
];
